name: remote ssh command
on:
  push:
    branches:
      - master
      - dev
    paths:
      - "account/**"
      - ".github/workflows/new-deploy-account.yml"
  workflow_dispatch:

jobs:
  new-deploy-account:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: touch ciwuzhere.txt
